"""add username column

Revision ID: 3501981f2879
Revises: 
Create Date: 2021-08-18 08:10:16.110236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3501981f2879'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_userTable_fname', table_name='userTable')
    op.drop_index('ix_userTable_lname', table_name='userTable')
    op.drop_table('userTable')
    op.add_column('users', sa.Column('username', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.create_table('userTable',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"userTable_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('fname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('lname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='userTable_pkey'),
    sa.UniqueConstraint('email', name='userTable_email_key')
    )
    op.create_index('ix_userTable_lname', 'userTable', ['lname'], unique=False)
    op.create_index('ix_userTable_fname', 'userTable', ['fname'], unique=False)
    # ### end Alembic commands ###
